// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import { describe, beforeEach, it } from 'vitest';
import { FileReference, fileReferences } from '../../file-references';

describe('when scanning a document with a trailing comment after a file directive', () => {
    let result: FileReference[];

    beforeEach(() => {
        result = fileReferences(['    file Screens/InvoiceLineReport.tsx  // generated by Arc']);
    });

    it('should find the reference', () => {
        result.should.have.lengthOf(1);
    });

    it('should leave the comment out of the path', () => {
        result[0].path.should.equal('Screens/InvoiceLineReport.tsx');
    });

    it('should span only the path', () => {
        result[0].endColumn.should.equal(result[0].startColumn + 'Screens/InvoiceLineReport.tsx'.length);
    });
});
